### ISSUE TITLE
Request: Expose the lubricant handler to data packs

### ISSUE THREAD

**Issue by MuteTiefling** [Flaxbeard/ImmersivePetroleum#223]
It seems like you have crafttweaker support to add new lubricant types, but it would be nice if this were available to data pack modification as well so KubeJS could access it. 

Thanks for your consideration :D

**Comment by TwistedGate** [comment]
there are the `lubricant` (IP) and `plantoil` (IE) tags, so anything in those 2 tags will be usable
by the lubricant handler now since IP  version `1.16.5-3.2.0-3`.

`lubricant` tag is set up to use 3mB/t (in a sense this is the "high value" tag)
`plantoil` tag is set up to 12mB/t (and this is the "low value" tag)

9b7f237790e2cd06d592ccfe36e0fd5c7bf1d70d
