### ISSUE TITLE
Request for Licence Clarification

### ISSUE THREAD

**Issue by TimTinkers** [Flaxbeard/ImmersivePetroleum#57]
@Flaxbeard 
I notice that you have no licence for this repository. As I understand it, this means the licence defaults to "all rights reserved" and only grants us the right to fork per GitHub's TOS. We are not, however, permitted to actually modify or compile this repository in any way.

I just want to stay above-board here before I try and add some of my desired changes into your mod. Is this your desired intent? I notice that you've merged pull requests recently, so is this something I should individually be requesting permission from you to do?

(I realize this might seem like a completely overblown question for Minecraft modding, which is just a hobby to so many of us. But I've accidentally stepped on some developer toes before and don't want to do anything against your wishes here.)

Thanks!

**Comment by Flaxbeard** [comment]
The license is as such to match the license requirements of Immersive Engineering. Though I'm personally an OSS proponent, BluSunrize has chosen to make IE visible source but not open and since I use IE code I must respect his decision there. Pull Requests and such should be fine since IE allows them.

**Comment by TimTinkers** [comment]
Thank you!
